export const AIRTABLE_ENDPOINT_URL = 'https://api.airtable.com';
export const ECOSYSTEM_PROJECTS_ALLOWED_CATEGORIES = [
    'AI',
    'Audit Firm',
    'CDP',
    'DeFi Tools',
    'DePin',
    'DEX',
    'DEX Aggregator',
    'GameFi',
    'Launchpad',
    'Lending',
    'Liquidity Manager',
    'Memecoin',
    'NFT',
    'NFT Marketplace',
    'Options',
    'OTC Marketplace',
    'Perpetuals',
    'Portfolio Tracker',
    'RWA',
    'Social Finance',
    'Stablecoin',
    'Yield & AssetManagement',
    'Yield Aggregator',
];
