import {
    Discord,
    EvaluationAndInterview,
    GitHub,
    GoogleScholar,
    Instagram,
    LinkedIn,
    Reddit,
    Telegram,
    XSocialIcon,
    Youtube,
} from '@repo/icons';

export const SOCIAL_LINKS = [
    {
        icon: Discord,
        url: 'https://discord.iota.org',
        isExternal: true,
        arialLabel: 'Discord Community',
        labels: {
            section: 'Discord Community',
            footer: 'Community',
        },
        visibility: ['section', 'footer'],
    },
    {
        icon: Discord,
        url: 'https://builders-discord.iota.org/',
        isExternal: true,
        arialLabel: 'Discord Builder',
        labels: {
            section: 'Discord Builder',
            footer: 'Builder',
        },
        visibility: ['section', 'footer'],
    },
    {
        title: 'Telegram',
        icon: Telegram,
        url: 'https://t.me/IOTA_Official_Community',
        isExternal: true,
        arialLabel: 'Telegram',
        visibility: ['section', 'footer'],
    },
    {
        title: 'Reddit',
        icon: Reddit,
        url: 'https://www.reddit.com/r/Iota/',
        isExternal: true,
        arialLabel: 'Reddit',
        visibility: ['section', 'footer'],
    },
    {
        title: 'Instagram',
        icon: Instagram,
        url: 'https://www.instagram.com/iotafoundation/',
        isExternal: true,
        arialLabel: 'Instagram',
        isSection: true,
        visibility: ['section'],
    },
    {
        title: 'X',
        icon: XSocialIcon,
        url: 'https://x.com/iota',
        isExternal: true,
        arialLabel: 'X',
        visibility: ['section', 'footer'],
    },
    {
        title: 'GitHub',
        icon: GitHub,
        url: 'https://github.com/iotaledger',
        isExternal: true,
        arialLabel: 'GitHub',
        visibility: ['section', 'footer'],
    },
    {
        title: 'YouTube',
        icon: Youtube,
        url: 'https://www.youtube.com/c/iotafoundation',
        isExternal: true,
        arialLabel: 'YouTube',
        visibility: ['section', 'footer'],
    },
    {
        title: 'Google Scholar',
        icon: GoogleScholar,
        url: 'https://scholar.google.com/citations?hl=en&user=_ZIH81gAAAAJ&view_op=list_works&sortby=pubdate',
        isExternal: true,
        arialLabel: 'Google Scholar',
        isFooter: true,
        visibility: ['footer'],
    },
    {
        title: 'LinkedIn',
        icon: LinkedIn,
        url: 'https://www.linkedin.com/company/iotafoundation/',
        isExternal: true,
        arialLabel: 'LinkedIn',
        visibility: ['section', 'footer'],
    },

    {
        title: 'Blog',
        icon: EvaluationAndInterview,
        url: 'https://blog.iota.org',
        isExternal: true,
        arialLabel: 'Blog',
        isSection: true,
        visibility: ['section'],
    },
];
