export { Hero as HeroIdentity } from './Hero';
export { IdentityOverview } from './IdentityOverview';
export { DigitalIdentity } from './DigitalIdentity';
export { HowItWorks } from './HowItWorks';
export { KeyCapabilities } from './KeyCapabilities';
export { WhyIota } from './WhyIota';
export { Tooling } from './Tooling';
export { ZeroKnowledge } from './ZeroKnowledge';
export { IdentityContactUs } from './IdentityContactUs';
export { IdentityMoreToExplore } from './IdentityMoreToExplore';
