export const BASE_URL = '/';

export const HOMEPAGE_METADATA_TITLE = '';
export const HOMEPAGE_METADATA_DESCRIPTION = '';
export const HOMEPAGE_METADATA_TITLE_X = '';
export const HOMEPAGE_METADATA_DESCRIPTION_X = '';
export const HOMEPAGE_KEYWORDS = [];
export const HOMEPAGE_URL = BASE_URL;
export const HOMEPAGE_IMAGE = '';

export const PURPOSE_METADATA_TITLE = '';
export const PURPOSE_METADATA_DESCRIPTION = '';
export const PURPOSE_METADATA_TITLE_X = '';
export const PURPOSE_METADATA_DESCRIPTION_X = '';
export const PURPOSE_KEYWORDS = [];
export const PURPOSE_URL = BASE_URL;
export const PURPOSE_IMAGE = '';

export const REGULATORY_AFFAIRS_METADATA_TITLE = '';
export const REGULATORY_AFFAIRS_METADATA_DESCRIPTION = '';
export const REGULATORY_AFFAIRS_METADATA_TITLE_X = '';
export const REGULATORY_AFFAIRS_METADATA_DESCRIPTION_X = '';
export const REGULATORY_AFFAIRS_KEYWORDS = [];
export const REGULATORY_AFFAIRS_URL = BASE_URL;
export const REGULATORY_AFFAIRS_IMAGE = '';

export const FOCUS_AREAS_METADATA_TITLE = '';
export const FOCUS_AREAS_METADATA_DESCRIPTION = '';
export const FOCUS_AREAS_METADATA_TITLE_X = '';
export const FOCUS_AREAS_METADATA_DESCRIPTION_X = '';
export const FOCUS_AREAS_KEYWORDS = [];
export const FOCUS_AREAS_URL = BASE_URL;
export const FOCUS_AREAS_IMAGE = '';

export const SHOWCASES_METADATA_TITLE = '';
export const SHOWCASES_METADATA_DESCRIPTION = '';
export const SHOWCASES_METADATA_TITLE_X = '';
export const SHOWCASES_METADATA_DESCRIPTION_X = '';
export const SHOWCASES_KEYWORDS = [];
export const SHOWCASES_URL = BASE_URL;
export const SHOWCASES_IMAGE = '';
