name: Production Deploy for the IOTALABS website

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy-production:
        uses: ./.github/workflows/monorepo-app-vercel-deploy.yml
        with:
            PRODUCTION: true
            APP_NAME: IOTALABS
            PACKAGE: iotalabs
        secrets: inherit
