name: Production Deploy for the IOTA Foundation website

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    detect:
        runs-on: ubuntu-latest
        outputs:
            packages: ${{ steps.detect.outputs.packages }}
        steps:
            - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # pin@v4.3.1
              with:
                  fetch-depth: 0
            - name: Detect changes
              id: detect
              uses: ./.github/actions/detect-changes

    deploy-production:
        needs: [detect]
        if: "contains(fromJson(needs.detect.outputs.packages), 'iota-foundation')"
        uses: ./.github/workflows/monorepo-app-vercel-deploy.yml
        with:
            PRODUCTION: true
            APP_NAME: IOTA Foundation
        secrets:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.IOTA_FOUNDATION_VERCEL_PROJECT_ID }}
            VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}

    purge-iota-foundation-cloudflare-cache:
        needs: [deploy-production]
        if: needs.deploy-production.result == 'success'
        uses: ./.github/workflows/purge-cloudfare-cache.yml
        with:
            IS_IOTA_FOUNDATION: true
        secrets:
            CLOUDFLARE_FOUNDATION_ZONE_ID: ${{ secrets.CLOUDFLARE_FOUNDATION_ZONE_ID }}
            CLOUDFLARE_CACHE_API_TOKEN: ${{ secrets.CLOUDFLARE_CACHE_API_TOKEN }}
