name: Production Deploy for the IOTA Network website

on:
    push:
        branches:
            - main
        paths:
            - 'apps/iota-network/**'
            - 'ui-kit/react/**'
            - 'shared/**'
            - '.github/workflows/iota-network.production-deploy.yml'
            - '.github/actions/monorepo-app-vercel-deploy/**'
    workflow_dispatch:

jobs:
    deploy-production:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
            deployments: write
        concurrency:
            group: ${{ github.workflow }}-IOTA Network-${{ github.ref }}
            cancel-in-progress: false
        steps:
            - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # pin@v4.3.1
            - uses: ./.github/actions/monorepo-app-vercel-deploy
              with:
                  production: 'true'
                  app_name: IOTA Network
                  vercel_token: ${{ secrets.VERCEL_TOKEN }}
                  vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
                  vercel_project_id: ${{ secrets.IOTA_NETWORK_VERCEL_PROJECT_ID }}
                  vercel_scope: ${{ secrets.VERCEL_SCOPE }}

    purge-iota-network-cloudflare-cache:
        needs: [deploy-production]
        uses: ./.github/workflows/purge-cloudfare-cache.yml
        with:
            IS_IOTA_NETWORK: true
        secrets:
            CLOUDFLARE_NETWORK_ZONE_ID: ${{ secrets.CLOUDFLARE_NETWORK_ZONE_ID }}
            CLOUDFLARE_CACHE_API_TOKEN: ${{ secrets.CLOUDFLARE_CACHE_API_TOKEN }}
