name: Preview Deploy for the IOTA Foundation website

on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    detect:
        runs-on: ubuntu-latest
        outputs:
            packages: ${{ steps.detect.outputs.packages }}
        steps:
            - name: Detect changes
              id: detect
              uses: ./.github/actions/detect-changes

    deploy-preview:
        needs: [detect]
        if: "contains(fromJson(needs.detect.outputs.packages), 'iota-foundation')"
        uses: ./.github/workflows/monorepo-app-vercel-deploy.yml
        with:
            PRODUCTION: false
            APP_NAME: IOTA Foundation
        secrets:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.IOTA_FOUNDATION_VERCEL_PROJECT_ID }}
            VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
