name: Preview Deploy fot the IOTA Foundation website

on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        paths:
            - 'apps/iota-foundation/**'
            - 'ui-kit/react/**'
            - '.github/workflows/iota-foundation.preview-deploy.yml'
            - '.github/workflows/monorepo-app-vercel-deploy.yml'
jobs:
    deploy-preview:
        uses: ./.github/workflows/monorepo-app-vercel-deploy.yml
        with:
            PRODUCTION: false
        secrets:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.IOTA_FOUNDATION_VERCEL_PROJECT_ID }}
            VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
