name: Monorepo App Vercel Deploy

on:
    workflow_call:
        inputs:
            PRODUCTION:
                type: boolean
                required: true
            APP_NAME:
                type: string
                required: true
        secrets:
            VERCEL_TOKEN:
                required: true
            VERCEL_ORG_ID:
                required: true
            VERCEL_PROJECT_ID:
                required: true
            VERCEL_SCOPE:
                required: true

env:
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_ENVIRONMENT: ${{ inputs.PRODUCTION && 'production' || 'preview' }}

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: ${{ inputs.PRODUCTION != true }}

jobs:
    vercel-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
            deployments: write
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # pin@v4.0.0

            - name: Install Vercel CLI
              run: pnpm add --global vercel@canary

            - name: Deploy to Vercel
              uses: iotaledger/deploy-to-vercel-action@d071db1f54f6ac69e812bdf0a6f271583d3a2f38
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
                  DELETE_EXISTING_COMMENT: true
                  VERCEL_TARGET: ${{ env.VERCEL_ENVIRONMENT }}
                  CREATE_COMMENT: ${{ env.VERCEL_ENVIRONMENT == 'preview' }}
                  COMMENT_IDENTIFIER: ${{ inputs.APP_NAME }}
                  ARCHIVE: tgz
