name: Preview Deploy

on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    iotalabs:
        uses: ./.github/workflows/monorepo-app-vercel-deploy.yml
        with:
            PRODUCTION: false
            APP_NAME: IOTALABS
            PACKAGE: iotalabs
        secrets: inherit

    iota-network:
        uses: ./.github/workflows/monorepo-app-vercel-deploy.yml
        with:
            PRODUCTION: false
            APP_NAME: IOTA Network
            PACKAGE: iota-network
        secrets: inherit

    iota-foundation:
        uses: ./.github/workflows/monorepo-app-vercel-deploy.yml
        with:
            PRODUCTION: false
            APP_NAME: IOTA Foundation
            PACKAGE: iota-foundation
        secrets: inherit

    react-ui-kit:
        uses: ./.github/workflows/monorepo-app-vercel-deploy.yml
        with:
            PRODUCTION: false
            APP_NAME: React UI-Kit Storybook
            PACKAGE: react-ui-kit
        secrets: inherit
