name: Production Deploy for the React UI Kit Storybook

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    detect:
        runs-on: ubuntu-latest
        outputs:
            packages: ${{ steps.detect.outputs.packages }}
        steps:
            - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # pin@v4.3.1
              with:
                  fetch-depth: 0
            - name: Detect changes
              id: detect
              uses: ./.github/actions/detect-changes

    deploy-production:
        needs: [detect]
        if: "contains(fromJson(needs.detect.outputs.packages), 'react-ui-kit')"
        uses: ./.github/workflows/monorepo-app-vercel-deploy.yml
        with:
            PRODUCTION: true
            APP_NAME: React UI-Kit Storybook
        secrets:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.REACT_UI_KIT_VERCEL_PROJECT_ID }}
            VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
