name: Production Deploy for the React UI Kit Storybook

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy-production:
        uses: ./.github/workflows/monorepo-app-vercel-deploy.yml
        with:
            PRODUCTION: true
            APP_NAME: React UI-Kit Storybook
            PACKAGE: react-ui-kit
        secrets: inherit
