name: Production Deploy for the React UI Kit Storybook

on:
    push:
        branches:
            - main
        paths:
            - 'ui-kit/react/**'
            - '.github/workflows/ui-kit-react.storybook-production-deploy.yml'
            - '.github/workflows/monorepo-app-vercel-deploy.yml'

env:
    WORKING_DIR: './ui-kit/react'

jobs:
    deploy-production:
        uses: ./.github/workflows/monorepo-app-vercel-deploy.yml
        with:
            WORKING_DIRECTORY: './ui-kit/react'
            PRODUCTION: true
        secrets:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.REACT_UI_KIT_VERCEL_PROJECT_ID }}
            VERCEL_PROJECT_NAME: ${{ secrets.REACT_UI_KIT_VERCEL_PROJECT_NAME }}
            VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
